# Generated by Django 4.2.4 on 2023-08-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
