# Generated by Django 4.2.4 on 2023-08-16 15:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_thumnail_game_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
