# Generated by Django 4.2.3 on 2023-08-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_game_slug_genre_slug_alter_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='thumnail',
            field=models.ImageField(null=True, upload_to='game_images'),
        ),
    ]
